apiVersion: apps/v1
kind: Deployment
metadada: 
  name: deploy-frontend
  labels:
    app: front-end
spec:
  selector:
      matchLabels:
        app: front-end
  template: 
    metadata:
      labels:
        app: front-end
    spec: 
      containers:
      - image: salomoneslaitendava/devopsrampup:frontendV2
        name: front-end
        ports:
        -containerPort: 3030
  replicas: 2
  