---
apiVersion: v1
kind: Deployment
metadada: 
  name: deploy-frontend
spec:
  template: 
    metadata:
      labels:
        tag: front-end
    spec: 
      containers:
      - name: front-end-name
        image: salomoneslaitendava/devopsrampup:frontendV2
  replicas: 2
  selector:
    matchLabels:
      tag: front-end