apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploy-backend
  labels:
    app: backend
spec:
  selector:
      matchLabels:
        app: backend
  template: 
    metadata:
      labels:
        app: backend
    spec: 
      containers:
      - image: salomoneslaitendava/devopsrampup-back:3
        name: backend
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "10.149.128.2"
        - name: DB_USER
          value: "root"
        - name: DB_PASS
          value: "admin"
        - name: DB_NAME
          value: "movie_db"
  replicas: 2
  