--- 
apiVersion: apps/v1
kind: Deployment
metadada: 
  name: deploy-frontend
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      tag: front-end
  template: 
    metadata: 
      labels: 
        tag: front-end
    spec: 
      containers: 
        - 
          image: "salomoneslaitendava/devopsrampup:frontendV2"
          name: front-end-name