--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: front-end-loadbalancer
  name: front-end-loadbalancer
spec: 
  ports: 
    - 
      port: 3030
      protocol: TCP
      targetPort: 3030
  selector: 
    app: front-end
  type: LoadBalancer
