--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: front-end-loadbalancer
  name: front-end-svc
spec: 
  ports: 
    - 
      name: http
      port: 3030
      protocol: TCP
      targetPort: 3030
  selector: 
    app: front-end-loadbalancer
  type: LoadBalancer
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: front-end-loadbalancer-deployment
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app.kubernetes.io/name: worker-node-1
  template: 
    metadata: 
      labels: 
        app: front-end-loadbalancer
    spec: 
      containers: 
        - 
          image: "salomoneslaitendava/devopsrampup:v2"
          name: front-end-loadbalancer-pod
          ports: 
            - 
              containerPort: 3030
